esphome:
  name: <your-esphome-entity-name>
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "<enter_wifi_ssid_here>"
  password: "<enter_wifi_password_here>"
  fast_connect: true
  power_save_mode: high
  # Static ip is recommended for faster connection times
  manual_ip:
    static_ip: <your_static_ip_here>
    gateway: <youer_gateway_here>
    subnet: 255.255.255.0
    dns1: <optionally_your_dns_server_here>

switch:
  platform: shutdown
  name: <your-sensor-name-shutdown>
  id: "shutdown"

binary_sensor:
  platform: status
  name: <your-sensor-name-here>
  device_class: window

sensor:
  platform: adc
  pin: VCC
  name: <your-sensor-name>-voltage

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
